'use strict'

require('PathFinder')
require('Room')
require('globals')
global.Grid = require('grid')
require('Market')
require('misc')
global.Body = require('prototype.Body')
require('prototype.Creep')
require('prototype.Number')
require('prototype.Object')
require('prototype.PowerCreep')
require('prototype.Room')
require('prototype.RoomObject')
require('prototype.RoomPosition')
global.RoomGrid = require('roomGrid')
require('roomPlan')
require('roomVisual')
